INSERT INTO roles (id, name, description, created_at, updated_at) VALUES
(1, 'ADMIN', 'Administrador', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'COORDINADOR', 'Coordinador', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'DESPACHADOR', 'Despachador', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'CONTADOR', 'Contador', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
