ALTER TABLE products ADD COLUMN price NUMERIC(18,2) NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN cost NUMERIC(18,2) NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN presentation INTEGER DEFAULT 0;
ALTER TABLE products ADD COLUMN weight VARCHAR(50);
ALTER TABLE products ADD COLUMN weight_grams INTEGER DEFAULT 0;
